export const SET_CHI_TIET_PHONG_VE = "SET_CHI_TIET_PHONG_VE";
export const DAT_VE = "DAT_VE"; // chọn ghế
export const CLEAR_DANG_SACH_GHE_DANG_CHON = "CLEAR_DANG_SACH_GHE_DANG_CHON";
export const CHANGE_TAB_PANE = "CHANGE_TAB_PANE";
export const SET_GHE_NGUOI_KHAC_DANG_CHON = "SET_GHE_NGUOI_KHAC_DANG_CHON";
